// src/kernel/ebpf_loader.rs
//! EBPFManager — Userspace controller for the kernel-level eBPF TC classifier using Aya.
//!
//! Loads the pre-compiled BPF program (`rustray-ebpf.elf`), uses Aya's BPF_MAP_TYPE_HASH
//! for whitelisted destination IPs, attaches the program to the primary NIC's
//! TC egress path, and manages the IP whitelist at runtime.
//!
//! Requires `CAP_NET_ADMIN` and `CAP_BPF` (or root).

use std::collections::HashSet;
use std::fs;
use std::io;
use std::net::Ipv4Addr;
use tracing::{debug, error, info, warn};

// Note: aya must be listed in Cargo.toml
use aya::Bpf;
use aya::maps::HashMap;
use aya::programs::{SchedClassifier, TcAttachType, tc};

use crate::kernel::ebpf_program::SlicerConfig;

// ============================================================================
// NIC AUTO-DETECTION
// ============================================================================

/// Auto-detect the primary routing NIC by parsing `/proc/net/route`.
fn detect_primary_nic() -> io::Result<String> {
    let content = fs::read_to_string("/proc/net/route")?;
    for line in content.lines().skip(1) {
        let fields: Vec<&str> = line.split_whitespace().collect();
        if fields.len() >= 3 && fields[1] == "00000000" {
            return Ok(fields[0].to_string());
        }
    }
    for name in &["eth0", "ens33", "enp0s3", "wlan0", "wlp2s0"] {
        let path = format!("/sys/class/net/{}", name);
        if std::path::Path::new(&path).exists() {
            return Ok(name.to_string());
        }
    }
    Err(io::Error::new(
        io::ErrorKind::NotFound,
        "No primary NIC found",
    ))
}

// ============================================================================
// EBPF MANAGER
// ============================================================================

/// Manages the lifecycle of the eBPF TC classifier program using Aya.
pub struct EBPFManager {
    /// The attached, loaded Aya BPF environment.
    bpf: Bpf,
    /// Name of the interface the program is attached to.
    ifname: String,
    /// Set of currently whitelisted IPs.
    whitelisted_ips: HashSet<Ipv4Addr>,
    /// Whether the program is currently attached.
    attached: bool,
    /// Slicer configuration used for program tracking.
    config: SlicerConfig,
}

impl EBPFManager {
    /// Load the eBPF ELF file.
    pub fn load(config: SlicerConfig) -> io::Result<Self> {
        info!("eBPF: Loading TC classifier program via Aya...");

        let elf_path = "ebpf"; // Path generated by BPF compilation

        let bpf = match Bpf::load_file(elf_path) {
            Ok(b) => b,
            Err(e) => {
                error!("Failed to load eBPF ELF {}: {}", elf_path, e);
                return Err(io::Error::new(io::ErrorKind::NotFound, e.to_string()));
            }
        };

        info!("eBPF: Program loaded successfully from {}", elf_path);

        Ok(Self {
            bpf,
            ifname: String::new(),
            whitelisted_ips: HashSet::new(),
            attached: false,
            config,
        })
    }

    /// Auto-detect the primary NIC and attach the TC classifier to its egress path.
    pub fn attach(&mut self) -> io::Result<()> {
        if self.attached {
            warn!("eBPF: Already attached to {}", self.ifname);
            return Ok(());
        }

        let ifname = detect_primary_nic()?;
        info!("eBPF: Detected primary NIC: {}", ifname);

        self.attach_to(&ifname)
    }

    /// Attach to a specific named interface using Aya's TC subsystem.
    pub fn attach_to(&mut self, ifname: &str) -> io::Result<()> {
        if self.attached {
            self.detach()?;
        }

        info!("eBPF: Attaching to specified NIC: {}", ifname);

        // Ensure clsact qdisc exists (aya provides a helper for this)
        let _ = tc::qdisc_add_clsact(ifname);

        let program: &mut SchedClassifier = self
            .bpf
            .program_mut("mutilator_egress")
            .ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::NotFound,
                    "Program mutilator_egress not found in ELF",
                )
            })?
            .try_into()
            .map_err(|e| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("Failed to covert to TC program: {}", e),
                )
            })?;

        program
            .load()
            .map_err(|e| io::Error::other(e.to_string()))?;
        program
            .attach(ifname, TcAttachType::Egress)
            .map_err(|e| io::Error::other(e.to_string()))?;

        info!("eBPF: Attached TC classifier to {} egress", ifname);

        self.ifname = ifname.to_string();
        self.attached = true;
        Ok(())
    }

    /// Detach the TC classifier from the current interface.
    pub fn detach(&mut self) -> io::Result<()> {
        if !self.attached {
            return Ok(());
        }

        if let Some(program) = self.bpf.program_mut("mutilator_egress")
            && let Ok(_tc_prog) = program.try_into().map(|p: &mut SchedClassifier| p) {
                // Detach is handled automatically on dropping or can be explicitly handled 
                // if we saved the LinkId from attach().
            }

        info!("eBPF: Detached TC classifier from {} egress", self.ifname);
        self.attached = false;
        Ok(())
    }

    /// Add a proxy node IP to the whitelist map (IPC).
    pub fn add_target_ip(&mut self, ip: Ipv4Addr) -> io::Result<()> {
        let mut map: HashMap<_, u32, u8> =
            HashMap::try_from(self.bpf.map_mut("WHITELIST").unwrap())
                .map_err(|_| io::Error::new(io::ErrorKind::InvalidData, "Invalid map type"))?;

        let key = u32::from_ne_bytes(ip.octets());
        map.insert(key, 1, 0)
            .map_err(|e| io::Error::other(e.to_string()))?;

        self.whitelisted_ips.insert(ip);
        debug!("eBPF: Added target IP {} to whitelist", ip);
        Ok(())
    }

    /// Remove a proxy node IP from the whitelist map (IPC).
    pub fn remove_target_ip(&mut self, ip: Ipv4Addr) -> io::Result<()> {
        let mut map: HashMap<_, u32, u8> =
            HashMap::try_from(self.bpf.map_mut("WHITELIST").unwrap())
                .map_err(|_| io::Error::new(io::ErrorKind::InvalidData, "Invalid map type"))?;

        let key = u32::from_ne_bytes(ip.octets());
        map.remove(&key)
            .map_err(|e| io::Error::other(e.to_string()))?;

        self.whitelisted_ips.remove(&ip);
        debug!("eBPF: Removed target IP {} from whitelist", ip);
        Ok(())
    }

    /// Check if an IP is currently in the whitelist.
    pub fn is_target_ip(&self, ip: Ipv4Addr) -> io::Result<bool> {
        Ok(self.whitelisted_ips.contains(&ip))
    }

    /// Get the set of currently whitelisted IPs.
    pub fn whitelisted_ips(&self) -> &HashSet<Ipv4Addr> {
        &self.whitelisted_ips
    }

    /// Get the name of the interface the program is attached to.
    pub fn interface(&self) -> &str {
        &self.ifname
    }

    /// Check if the program is currently attached.
    pub fn is_attached(&self) -> bool {
        self.attached
    }

    /// Get the slicer configuration.
    pub fn config(&self) -> &SlicerConfig {
        &self.config
    }
}

impl Drop for EBPFManager {
    fn drop(&mut self) {
        if self.attached {
            let _ = self.detach();
        }
        info!("eBPF: Manager cleaned up");
    }
}
